"""Integration adapters for external services and tooling."""

from contracting_hub.integrations.playground import (
    PLAYGROUND_DEPLOYMENT_CHANNEL,
    PlaygroundAdapter,
    PlaygroundAdapterCapabilities,
    PlaygroundAdapterError,
    PlaygroundAdapterErrorCode,
    PlaygroundContractPayload,
    PlaygroundDeploymentRequest,
    PlaygroundDeploymentResult,
    PlaygroundDispatchStatus,
    PlaygroundTransport,
)
from contracting_hub.integrations.storage import (
    IMAGE_UPLOAD_CONTENT_TYPES,
    IMAGE_UPLOAD_EXTENSIONS,
    FileStorage,
    LocalFileStorage,
    StoredUpload,
    UploadCandidate,
    UploadConstraints,
    UploadValidationError,
    UploadValidationErrorCode,
    UploadValidator,
    avatar_upload_constraints,
    validate_content_type,
    validate_extension,
    validate_max_bytes,
    validate_not_empty,
    validate_upload,
)

__all__ = [
    "PLAYGROUND_DEPLOYMENT_CHANNEL",
    "PlaygroundAdapter",
    "PlaygroundAdapterCapabilities",
    "PlaygroundAdapterError",
    "PlaygroundAdapterErrorCode",
    "PlaygroundContractPayload",
    "PlaygroundDeploymentRequest",
    "PlaygroundDeploymentResult",
    "PlaygroundDispatchStatus",
    "PlaygroundTransport",
    "FileStorage",
    "IMAGE_UPLOAD_CONTENT_TYPES",
    "IMAGE_UPLOAD_EXTENSIONS",
    "LocalFileStorage",
    "StoredUpload",
    "UploadCandidate",
    "UploadConstraints",
    "UploadValidationError",
    "UploadValidationErrorCode",
    "UploadValidator",
    "avatar_upload_constraints",
    "validate_content_type",
    "validate_extension",
    "validate_max_bytes",
    "validate_not_empty",
    "validate_upload",
]
