"""initial schema

Revision ID: 9db45bd4585d
Revises:
Create Date: 2026-03-09 04:38:21.716482

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9db45bd4585d"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("slug", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("categories", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_categories_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_categories_name"), ["name"], unique=True)
        batch_op.create_index(batch_op.f("ix_categories_slug"), ["slug"], unique=True)
        batch_op.create_index(batch_op.f("ix_categories_sort_order"), ["sort_order"], unique=False)
        batch_op.create_index(batch_op.f("ix_categories_updated_at"), ["updated_at"], unique=False)

    op.create_table(
        "contract_versions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("contract_id", sa.Integer(), nullable=False),
        sa.Column("semantic_version", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
        sa.Column(
            "status",
            sa.Enum("DRAFT", "PUBLISHED", "ARCHIVED", "DEPRECATED", name="publicationstatus"),
            nullable=False,
        ),
        sa.Column("source_code", sa.Text(), nullable=False),
        sa.Column(
            "source_hash_sha256", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False
        ),
        sa.Column("changelog", sa.Text(), nullable=True),
        sa.Column("previous_version_id", sa.Integer(), nullable=True),
        sa.Column("lint_status", sa.Enum("PASS", "WARN", "FAIL", name="lintstatus"), nullable=True),
        sa.Column("lint_summary", sa.JSON(), nullable=True),
        sa.Column("lint_results", sa.JSON(), nullable=True),
        sa.Column("diff_summary", sa.JSON(), nullable=True),
        sa.Column("published_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["contract_id"],
            ["contracts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["previous_version_id"],
            ["contract_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "contract_id", "semantic_version", name="uq_contract_versions_contract_semantic_version"
        ),
    )
    with op.batch_alter_table("contract_versions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_contract_versions_contract_id"), ["contract_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_contract_versions_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_contract_versions_lint_status"), ["lint_status"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_contract_versions_previous_version_id"),
            ["previous_version_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_contract_versions_published_at"), ["published_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_contract_versions_semantic_version"), ["semantic_version"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_contract_versions_source_hash_sha256"),
            ["source_hash_sha256"],
            unique=False,
        )
        batch_op.create_index(batch_op.f("ix_contract_versions_status"), ["status"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_contract_versions_updated_at"), ["updated_at"], unique=False
        )

    op.create_table(
        "contracts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("slug", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
        sa.Column("contract_name", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column("display_name", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
        sa.Column("short_summary", sqlmodel.sql.sqltypes.AutoString(length=280), nullable=False),
        sa.Column("long_description", sa.Text(), nullable=False),
        sa.Column("author_user_id", sa.Integer(), nullable=True),
        sa.Column("author_label", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
        sa.Column(
            "status",
            sa.Enum("DRAFT", "PUBLISHED", "ARCHIVED", "DEPRECATED", name="publicationstatus"),
            nullable=False,
        ),
        sa.Column("featured", sa.Boolean(), nullable=False),
        sa.Column("license_name", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
        sa.Column("documentation_url", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
        sa.Column(
            "source_repository_url", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True
        ),
        sa.Column(
            "network",
            sa.Enum("SANDBOX", "TESTNET", "MAINNET_COMPATIBLE", name="contractnetwork"),
            nullable=True,
        ),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("latest_published_version_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["author_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["latest_published_version_id"],
            ["contract_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("contracts", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_contracts_author_user_id"), ["author_user_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_contracts_contract_name"), ["contract_name"], unique=True
        )
        batch_op.create_index(batch_op.f("ix_contracts_created_at"), ["created_at"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_contracts_display_name"), ["display_name"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_contracts_featured"), ["featured"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_contracts_latest_published_version_id"),
            ["latest_published_version_id"],
            unique=False,
        )
        batch_op.create_index(batch_op.f("ix_contracts_network"), ["network"], unique=False)
        batch_op.create_index(batch_op.f("ix_contracts_slug"), ["slug"], unique=True)
        batch_op.create_index(batch_op.f("ix_contracts_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_contracts_updated_at"), ["updated_at"], unique=False)

    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(length=320), nullable=False),
        sa.Column("password_hash", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("role", sa.Enum("USER", "ADMIN", name="userrole"), nullable=False),
        sa.Column("status", sa.Enum("ACTIVE", "DISABLED", name="userstatus"), nullable=False),
        sa.Column("last_login_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=True)
        batch_op.create_index(batch_op.f("ix_users_last_login_at"), ["last_login_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_users_role"), ["role"], unique=False)
        batch_op.create_index(batch_op.f("ix_users_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_users_updated_at"), ["updated_at"], unique=False)

    op.create_table(
        "admin_audit_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("admin_user_id", sa.Integer(), nullable=False),
        sa.Column("action", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column("entity_type", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column("entity_id", sa.Integer(), nullable=True),
        sa.Column("summary", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["admin_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("admin_audit_logs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_admin_audit_logs_action"), ["action"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_admin_audit_logs_admin_user_id"), ["admin_user_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_admin_audit_logs_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_admin_audit_logs_entity_id"), ["entity_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_admin_audit_logs_entity_type"), ["entity_type"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_admin_audit_logs_updated_at"), ["updated_at"], unique=False
        )

    op.create_table(
        "contract_category_links",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("contract_id", sa.Integer(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["contract_id"],
            ["contracts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "contract_id", "category_id", name="uq_contract_category_links_contract_category"
        ),
    )
    with op.batch_alter_table("contract_category_links", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_contract_category_links_category_id"), ["category_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_contract_category_links_contract_id"), ["contract_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_contract_category_links_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_contract_category_links_is_primary"), ["is_primary"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_contract_category_links_sort_order"), ["sort_order"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_contract_category_links_updated_at"), ["updated_at"], unique=False
        )

    op.create_table(
        "contract_relations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("source_contract_id", sa.Integer(), nullable=False),
        sa.Column("target_contract_id", sa.Integer(), nullable=False),
        sa.Column(
            "relation_type",
            sa.Enum(
                "DEPENDS_ON",
                "COMPANION",
                "EXAMPLE_FOR",
                "EXTENDS",
                "SUPERSEDES",
                name="contractrelationtype",
            ),
            nullable=False,
        ),
        sa.Column("note", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.CheckConstraint(
            "source_contract_id != target_contract_id",
            name="ck_contract_relations_distinct_contracts",
        ),
        sa.ForeignKeyConstraint(
            ["source_contract_id"],
            ["contracts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["target_contract_id"],
            ["contracts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "source_contract_id",
            "target_contract_id",
            "relation_type",
            name="uq_contract_relations_source_target_type",
        ),
    )
    with op.batch_alter_table("contract_relations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_contract_relations_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_contract_relations_relation_type"), ["relation_type"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_contract_relations_source_contract_id"),
            ["source_contract_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_contract_relations_target_contract_id"),
            ["target_contract_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_contract_relations_updated_at"), ["updated_at"], unique=False
        )

    op.create_table(
        "playground_targets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("label", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column("playground_id", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("last_used_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "playground_id", name="uq_playground_targets_user_playground_id"
        ),
    )
    with op.batch_alter_table("playground_targets", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_playground_targets_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_playground_targets_is_default"), ["is_default"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_playground_targets_last_used_at"), ["last_used_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_playground_targets_playground_id"), ["playground_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_playground_targets_updated_at"), ["updated_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_playground_targets_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "profiles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("username", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
        sa.Column("display_name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
        sa.Column("bio", sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
        sa.Column("avatar_path", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
        sa.Column("website_url", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
        sa.Column("github_url", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
        sa.Column("xian_profile_url", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("profiles", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_profiles_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_profiles_updated_at"), ["updated_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_profiles_user_id"), ["user_id"], unique=True)
        batch_op.create_index(batch_op.f("ix_profiles_username"), ["username"], unique=True)

    op.create_table(
        "ratings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("contract_id", sa.Integer(), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("note", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
        sa.CheckConstraint("score >= 1 AND score <= 5", name="ck_ratings_score_range"),
        sa.ForeignKeyConstraint(
            ["contract_id"],
            ["contracts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "contract_id", name="uq_ratings_user_contract"),
    )
    with op.batch_alter_table("ratings", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_ratings_contract_id"), ["contract_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_ratings_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_ratings_score"), ["score"], unique=False)
        batch_op.create_index(batch_op.f("ix_ratings_updated_at"), ["updated_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_ratings_user_id"), ["user_id"], unique=False)

    op.create_table(
        "stars",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("contract_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["contract_id"],
            ["contracts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "contract_id", name="uq_stars_user_contract"),
    )
    with op.batch_alter_table("stars", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_stars_contract_id"), ["contract_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_stars_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_stars_updated_at"), ["updated_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_stars_user_id"), ["user_id"], unique=False)

    op.create_table(
        "deployment_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("contract_version_id", sa.Integer(), nullable=False),
        sa.Column("playground_target_id", sa.Integer(), nullable=True),
        sa.Column("playground_id", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "ACCEPTED", "REDIRECT_REQUIRED", "FAILED", name="deploymentstatus"),
            nullable=False,
        ),
        sa.Column(
            "transport",
            sa.Enum("DEEP_LINK", "HTTP", "HYBRID", name="deploymenttransport"),
            nullable=True,
        ),
        sa.Column(
            "external_request_id", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True
        ),
        sa.Column("redirect_url", sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
        sa.Column("request_payload", sa.JSON(), nullable=False),
        sa.Column("response_payload", sa.JSON(), nullable=True),
        sa.Column("error_payload", sa.JSON(), nullable=True),
        sa.Column("initiated_at", sa.DateTime(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["contract_version_id"],
            ["contract_versions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["playground_target_id"],
            ["playground_targets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("deployment_history", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_deployment_history_completed_at"), ["completed_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_deployment_history_contract_version_id"),
            ["contract_version_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_deployment_history_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_deployment_history_external_request_id"),
            ["external_request_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_deployment_history_initiated_at"), ["initiated_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_deployment_history_playground_id"), ["playground_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_deployment_history_playground_target_id"),
            ["playground_target_id"],
            unique=False,
        )
        batch_op.create_index(batch_op.f("ix_deployment_history_status"), ["status"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_deployment_history_transport"), ["transport"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_deployment_history_updated_at"), ["updated_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_deployment_history_user_id"), ["user_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("deployment_history", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_deployment_history_user_id"))
        batch_op.drop_index(batch_op.f("ix_deployment_history_updated_at"))
        batch_op.drop_index(batch_op.f("ix_deployment_history_transport"))
        batch_op.drop_index(batch_op.f("ix_deployment_history_status"))
        batch_op.drop_index(batch_op.f("ix_deployment_history_playground_target_id"))
        batch_op.drop_index(batch_op.f("ix_deployment_history_playground_id"))
        batch_op.drop_index(batch_op.f("ix_deployment_history_initiated_at"))
        batch_op.drop_index(batch_op.f("ix_deployment_history_external_request_id"))
        batch_op.drop_index(batch_op.f("ix_deployment_history_created_at"))
        batch_op.drop_index(batch_op.f("ix_deployment_history_contract_version_id"))
        batch_op.drop_index(batch_op.f("ix_deployment_history_completed_at"))

    op.drop_table("deployment_history")
    with op.batch_alter_table("stars", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_stars_user_id"))
        batch_op.drop_index(batch_op.f("ix_stars_updated_at"))
        batch_op.drop_index(batch_op.f("ix_stars_created_at"))
        batch_op.drop_index(batch_op.f("ix_stars_contract_id"))

    op.drop_table("stars")
    with op.batch_alter_table("ratings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ratings_user_id"))
        batch_op.drop_index(batch_op.f("ix_ratings_updated_at"))
        batch_op.drop_index(batch_op.f("ix_ratings_score"))
        batch_op.drop_index(batch_op.f("ix_ratings_created_at"))
        batch_op.drop_index(batch_op.f("ix_ratings_contract_id"))

    op.drop_table("ratings")
    with op.batch_alter_table("profiles", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_profiles_username"))
        batch_op.drop_index(batch_op.f("ix_profiles_user_id"))
        batch_op.drop_index(batch_op.f("ix_profiles_updated_at"))
        batch_op.drop_index(batch_op.f("ix_profiles_created_at"))

    op.drop_table("profiles")
    with op.batch_alter_table("playground_targets", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_playground_targets_user_id"))
        batch_op.drop_index(batch_op.f("ix_playground_targets_updated_at"))
        batch_op.drop_index(batch_op.f("ix_playground_targets_playground_id"))
        batch_op.drop_index(batch_op.f("ix_playground_targets_last_used_at"))
        batch_op.drop_index(batch_op.f("ix_playground_targets_is_default"))
        batch_op.drop_index(batch_op.f("ix_playground_targets_created_at"))

    op.drop_table("playground_targets")
    with op.batch_alter_table("contract_relations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_contract_relations_updated_at"))
        batch_op.drop_index(batch_op.f("ix_contract_relations_target_contract_id"))
        batch_op.drop_index(batch_op.f("ix_contract_relations_source_contract_id"))
        batch_op.drop_index(batch_op.f("ix_contract_relations_relation_type"))
        batch_op.drop_index(batch_op.f("ix_contract_relations_created_at"))

    op.drop_table("contract_relations")
    with op.batch_alter_table("contract_category_links", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_contract_category_links_updated_at"))
        batch_op.drop_index(batch_op.f("ix_contract_category_links_sort_order"))
        batch_op.drop_index(batch_op.f("ix_contract_category_links_is_primary"))
        batch_op.drop_index(batch_op.f("ix_contract_category_links_created_at"))
        batch_op.drop_index(batch_op.f("ix_contract_category_links_contract_id"))
        batch_op.drop_index(batch_op.f("ix_contract_category_links_category_id"))

    op.drop_table("contract_category_links")
    with op.batch_alter_table("admin_audit_logs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_admin_audit_logs_updated_at"))
        batch_op.drop_index(batch_op.f("ix_admin_audit_logs_entity_type"))
        batch_op.drop_index(batch_op.f("ix_admin_audit_logs_entity_id"))
        batch_op.drop_index(batch_op.f("ix_admin_audit_logs_created_at"))
        batch_op.drop_index(batch_op.f("ix_admin_audit_logs_admin_user_id"))
        batch_op.drop_index(batch_op.f("ix_admin_audit_logs_action"))

    op.drop_table("admin_audit_logs")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_updated_at"))
        batch_op.drop_index(batch_op.f("ix_users_status"))
        batch_op.drop_index(batch_op.f("ix_users_role"))
        batch_op.drop_index(batch_op.f("ix_users_last_login_at"))
        batch_op.drop_index(batch_op.f("ix_users_email"))
        batch_op.drop_index(batch_op.f("ix_users_created_at"))

    op.drop_table("users")
    with op.batch_alter_table("contracts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_contracts_updated_at"))
        batch_op.drop_index(batch_op.f("ix_contracts_status"))
        batch_op.drop_index(batch_op.f("ix_contracts_slug"))
        batch_op.drop_index(batch_op.f("ix_contracts_network"))
        batch_op.drop_index(batch_op.f("ix_contracts_latest_published_version_id"))
        batch_op.drop_index(batch_op.f("ix_contracts_featured"))
        batch_op.drop_index(batch_op.f("ix_contracts_display_name"))
        batch_op.drop_index(batch_op.f("ix_contracts_created_at"))
        batch_op.drop_index(batch_op.f("ix_contracts_contract_name"))
        batch_op.drop_index(batch_op.f("ix_contracts_author_user_id"))

    op.drop_table("contracts")
    with op.batch_alter_table("contract_versions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_contract_versions_updated_at"))
        batch_op.drop_index(batch_op.f("ix_contract_versions_status"))
        batch_op.drop_index(batch_op.f("ix_contract_versions_source_hash_sha256"))
        batch_op.drop_index(batch_op.f("ix_contract_versions_semantic_version"))
        batch_op.drop_index(batch_op.f("ix_contract_versions_published_at"))
        batch_op.drop_index(batch_op.f("ix_contract_versions_previous_version_id"))
        batch_op.drop_index(batch_op.f("ix_contract_versions_lint_status"))
        batch_op.drop_index(batch_op.f("ix_contract_versions_created_at"))
        batch_op.drop_index(batch_op.f("ix_contract_versions_contract_id"))

    op.drop_table("contract_versions")
    with op.batch_alter_table("categories", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_categories_updated_at"))
        batch_op.drop_index(batch_op.f("ix_categories_sort_order"))
        batch_op.drop_index(batch_op.f("ix_categories_slug"))
        batch_op.drop_index(batch_op.f("ix_categories_name"))
        batch_op.drop_index(batch_op.f("ix_categories_created_at"))

    op.drop_table("categories")
    # ### end Alembic commands ###
